### PR TITLE
+ Add Krisna Page

### PR DESCRIPTION
**Pull request by oishiiLatte**
Tambahin dong

### CODE REVIEW

**Comment by dyahisnaeny** [comment]
biar apa ini

**Comment by parksama** [comment]
Krisna tolong diresolve dulu yaaa

**Comment by harasya** [comment]
ra waton kowe kris

**Comment by endryningtyas** [comment]
kok iso conflict e Kris?

**Comment by devara** [comment]
Santai, santaiii

**Comment by oishiiLatte** [comment]
Sante lo, tak kandakke bapakku ngko

**Comment by dyahisnaeny** [comment]
> kok iso conflict e Kris?

hayo kui krisna waton

**Pull request merged**
